### ISSUE TITLE
Question and Feature request: save non-voters in membership

### ISSUE THREAD

**Issue by drmingdrmer** [async-raft/async-raft#116]
In my cluster a raft group acts as the metadata center: typically 5 candidates and many non-voters. A non-voter node just replicates logs and acts as metadata cache on every server.

A server needs to set up the replication from leader to non-voters once a leader is established because the non-voter list is not persisted on disk.

Would it be OK to save all the non-voters on disk, as part of the `membership`?

Any advice would be appreciated.

redirected from #114

**Comment by thedodd** [comment]
We should be able to do this. We will need to:
- add a new field to the `MembershipConfig` object to track non-voters which are being synced with the cluster,
- the leader code will need to be updated to add new members to that field instead of its in-memory struct field,
- the leader code will need to be updated to commit the new config object to the cluster, but it must not treat that config as joint consensus.

If we do the above, then it should be perfectly safe. Thoughts?
