### ISSUE TITLE
Is it possible to call `Storage::get_membership_config` directly here?

### ISSUE THREAD

**Issue by sunli829** [async-raft/async-raft#85]
I have stored the latest membership in storage, so that I can have better performance.

https://github.com/async-raft/async-raft/blob/f5f9a415e32cbd16d4312fd98d29eac77f31ae1f/async-raft/src/core/client.rs#L62

---------------

Since commit_index is always initialized to 0, I need to load all the logs every time I start raft.

https://github.com/async-raft/async-raft/blob/f5f9a415e32cbd16d4312fd98d29eac77f31ae1f/async-raft/src/core/mod.rs#L149

---------------

Please don't mind if I misunderstand this code. 🙂

**Comment by thedodd** [comment]
So, the implementation of the code here is going to be slightly more constrained than what the normal `Storage::get_membership_config` would be. We need to ensure that we do not go further back than `stale_logs_stop` in this case.

There is no performance concern here though. Although `commit_index` is initialized to `0`, it is always updated when heartbeats are received when running as a follower, and in order to become leader it must have an up-to-date log which means that its `commit_index` would not be zero unless there are really `0` logs. The practicality of other scenarios is low, and only impose a one time cost. Once the cluster is started, there will be no performance overhead from this routine.

Thoughts?

**Comment by sunli829** [comment]
Thank you for your answer, it seems that I have to think of other ways to optimize performance.
